name: Build Client

on:
  push:
    branches:
      - main

jobs:
  build-client:
    name: Build Client
    runs-on: ubuntu-latest

    steps:
      - name: Checkout client repo
        uses: actions/checkout@latest

      - name: Setup Node
        uses: actions/setup-node@latest
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build client
        run: npm run build

      - name: Upload build files
        uses: actions/upload-artifact@v4
        with:
          name: client-production-files
          path: ./dist
