name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: workout_db
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin123
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout frontend repo code
        uses: actions/checkout@v4

      - name: Checkout server repo code
        uses: actions/checkout@v4
        with:
          repository: UniSunshineCoast/csc301-24-assignment-3-secondary-Ricardo-USC
          token: ${{ secrets.REPO_TOKEN }}
          path: server

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install frontend dependencies
        run: npm install

      - name: Install server dependencies
        run: |
              cd server
              npm install

      - name: Start the server
        run: |
          cd server
          npm start &
          npx wait-on http://localhost:3030

      - name: Start frontend server
        run: |
          npm run dev &
          npx wait-on http://localhost:5173

      - name: Run Cypress e2e tests
        uses: cypress-io/github-action@v2
        with:
          start: npm run dev
          wait-on: http://localhost:5173
          wait-on-timeout: 120
          config-file: cypress.config.js
