name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout frontend code
        uses: actions/checkout@v4

      - name: Checkout backend code
        uses: actions/checkout@v4
        with:
          repository: UniSunshineCoast/csc301-24-assignment-3-secondary-Ricardo-USC
          token: ${{ secrets.REPO_TOKEN }}
          path: backend

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install frontend dependencies
        run: npm install

      - name: Install backend dependencies
        run: npm install
        working-directory: ./backend

      - name: Start services using Docker Compose
        run: |
          cd backend
          docker-compose up -d
        # env:
        #   POSTGRES_DB: workout_db
        #   POSTGRES_USER: admin
        #   POSTGRES_PASSWORD: admin123

      - name: Wait for backend to be ready
        run: npx wait-on http://localhost:3030

      - name: Start frontend server
        run: |
          npm run dev &
          npx wait-on http://localhost:5173

      - name: Run Cypress e2e tests
        uses: cypress-io/github-action@v2
        with:
          start: npm run dev
          wait-on: http://localhost:5173
          wait-on-timeout: 120
          config-file: cypress.config.js
